"use client";

import {
  getJobDocumentStateAction,
  triggerCoverLetterAction,
} from "@/app/actions/documents";
import DocumentPreviewOverlay from "@/components/DocumentPreviewOverlay";
import DotLoader from "@/components/DotLoader";
import { useJobState } from "@/components/JobStateProvider";
import { coverLetterStatusCopy } from "@/lib/funnel";
import { useEffect, useState } from "react";

const TONE_TEXT: Record<string, string> = {
  neutral: "text-zinc-500 dark:text-zinc-400",
  active: "text-indigo-600 dark:text-indigo-400",
  success: "text-emerald-600 dark:text-emerald-400",
  error: "text-rose-600 dark:text-rose-400",
};

/**
 * Cover letter for THIS job — generated by its OWN Azure Function + Service
 * Bus queue (`coverLetterWorker`), independent of the resume and evaluation.
 * For fit jobs it auto-generates when the evaluation scores the job; the
 * "Generate" button is the fallback/retry path.
 *
 * - `building` → shows "Writing your cover letter…" and listens live.
 * - `completed` → View (unified overlay) / Fine-tune.
 * - `none` → a Generate button.
 * - `failed` → error + Retry.
 *
 * A page refresh mid-generation re-hydrates `building`, so generation is
 * never cut off.
 */
export default function CoverLetterGenerationCard({
  jobId,
  title,
  company,
}: {
  jobId: string;
  title: string;
  company: string;
}) {
  // Shared live state (single socket + Realtime channel via JobStateProvider).
  const { coverLetterStatus, error: realtimeError } = useJobState();
  const [requesting, setRequesting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  // Optimistic local override: show "Writing…" immediately after triggering
  // instead of waiting for the Realtime/socket round-trip.
  const [optimisticBuilding, setOptimisticBuilding] = useState(false);
  // Unified preview overlay (Resume | Cover Letter tabs).
  const [previewOpen, setPreviewOpen] = useState(false);
  // Fine-tune overlay: user enters a refinement note, we regenerate the letter
  // with that instruction appended to the prompt.
  const [fineTuneOpen, setFineTuneOpen] = useState(false);
  const [refinement, setRefinement] = useState("");
  // True while a fine-tune regeneration is in flight — shows a
  // "Regenerating…" state in the overlay so the user knows it's processing.
  const [regenerating, setRegenerating] = useState(false);

  const status =
    coverLetterStatus === "completed" || coverLetterStatus === "failed"
      ? coverLetterStatus
      : optimisticBuilding || coverLetterStatus === "building"
        ? "building"
        : (coverLetterStatus ?? "none");
  const copy = coverLetterStatusCopy(status);
  const isBuilding = status === "building" || requesting;
  const isDone = status === "completed";
  const error = actionError ?? realtimeError;

  async function handleGenerate() {
    setActionError(null);
    setRequesting(true);
    const res = await triggerCoverLetterAction(jobId);
    setRequesting(false);
    if (!res.ok) {
      setActionError(
        /resume/i.test(res.error)
          ? "Upload a resume first, then try again."
          : "Couldn't start your cover letter. Please try again in a moment.",
      );
      return;
    }
    // Success → optimistically show "Writing your cover letter…" now.
    setOptimisticBuilding(true);
  }

  async function handleGenerateWithRefinement() {
    const note = refinement.trim();
    if (!note) {
      setActionError("Tell us what to change before regenerating.");
      return;
    }
    setActionError(null);
    setRegenerating(true);
    setRequesting(true);
    const res = await triggerCoverLetterAction(jobId, note);
    setRequesting(false);
    if (!res.ok) {
      setRegenerating(false);
      setActionError(
        /resume/i.test(res.error)
          ? "Upload a resume first, then try again."
          : "Couldn't regenerate your cover letter. Please try again in a moment.",
      );
      return;
    }
    // Success → show "Regenerating…" + the card's building state. Realtime /
    // socket confirm `building` → `completed` (see the effect below that
    // clears `regenerating` at a terminal state). No auto-open — the user can
    // open the preview from the card or the overlay's version nav bar.
    setOptimisticBuilding(true);
    setRefinement("");
  }

  // Clear the "Regenerating…" overlay state once the server reaches a
  // TERMINAL state (completed or failed). Without this, the fine-tune overlay
  // would sit on "Regenerating…" forever — the stale loop the user hit.
  useEffect(() => {
    if (coverLetterStatus === "completed" || coverLetterStatus === "failed") {
      setRegenerating(false);
      setOptimisticBuilding(false);
      setFineTuneOpen(false);
      if (coverLetterStatus === "failed") {
        setActionError("The refinement didn't finish. You can try again.");
      }
    }
  }, [coverLetterStatus]);

  // Guaranteed fallback while a fine-tune regeneration is in flight: poll the
  // document state so the "Regenerating…" overlay ALWAYS clears to the real
  // terminal state, even if the socket/Realtime event is missed.
  useEffect(() => {
    if (!regenerating || !jobId) return;
    let alive = true;
    async function check() {
      if (!alive) return;
      const res = await getJobDocumentStateAction(jobId);
      if (!alive || !res.ok) return;
      if (res.state.cover_letter_status === "completed") {
        setRegenerating(false);
        setOptimisticBuilding(false);
        setFineTuneOpen(false);
      } else if (res.state.cover_letter_status === "failed") {
        setRegenerating(false);
        setOptimisticBuilding(false);
        setFineTuneOpen(false);
        setActionError("The refinement didn't finish. You can try again.");
      }
    }
    void check();
    const interval = setInterval(check, 3000);
    return () => {
      alive = false;
      clearInterval(interval);
    };
  }, [regenerating, jobId]);

  return (
    <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5">
      <div className="flex items-center justify-between gap-3 mb-3">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-zinc-400 dark:text-zinc-500">
          Cover Letter
        </h2>
        <span className={`text-xs font-medium ${TONE_TEXT[copy.tone]}`}>
          {copy.label}
        </span>
      </div>

      {isBuilding ? (
        <div className="flex items-center gap-3">
          <DotLoader dotClassName="bg-indigo-500" />
          <div>
            <p className="text-sm font-medium text-indigo-700 dark:text-indigo-300">
              Writing your cover letter for {company}
            </p>
            <p className="text-xs text-indigo-500 dark:text-indigo-400">
              Usually takes under a minute. You can leave this page.
            </p>
          </div>
        </div>
      ) : isDone ? (
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => setPreviewOpen(true)}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
              />
            </svg>
            View cover letter
          </button>
          <button
            type="button"
            onClick={() => setFineTuneOpen(true)}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg border border-zinc-300 dark:border-zinc-600 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
              />
            </svg>
            Fine-tune
          </button>
        </div>
      ) : (
        <>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-4">
            Generate a cover letter for {title} at {company} — addressed to the
            role and grounded in your resume.
          </p>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={requesting}
            className="inline-flex items-center gap-2 text-sm font-medium px-4 py-2 rounded-xl border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 hover:bg-indigo-50 dark:hover:bg-indigo-950/60 transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 4v16m8-8H4"
              />
            </svg>
            {requesting ? "Starting…" : "Generate cover letter"}
          </button>
        </>
      )}

      {error && (
        <p className="mt-3 text-xs text-red-600 dark:text-red-400">{error}</p>
      )}

      {/* Fine-tune overlay — user tells us what to change, we regenerate the
          letter with that note (plus the base resume + full job content). */}
      {fineTuneOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
          onClick={() => setFineTuneOpen(false)}
        >
          <div
            className="relative w-full max-w-lg rounded-2xl bg-white dark:bg-zinc-900 shadow-2xl border border-zinc-200 dark:border-zinc-700 p-6"
            onClick={(e) => e.stopPropagation()}
          >
            {regenerating ? (
              <div className="flex items-center gap-3 py-4">
                <DotLoader dotClassName="bg-indigo-500" />
                <p className="text-sm font-medium text-indigo-700 dark:text-indigo-300">
                  Regenerating your cover letter…
                </p>
              </div>
            ) : (
              <>
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-50">
                    Fine-tune your cover letter
                  </h3>
                  <button
                    onClick={() => setFineTuneOpen(false)}
                    className="flex items-center justify-center w-8 h-8 rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800 text-zinc-500 dark:text-zinc-400 transition-colors"
                    aria-label="Close"
                  >
                    <svg
                      className="w-5 h-5"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth={2}
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M6 18L18 6M6 6l12 12"
                      />
                    </svg>
                  </button>
                </div>
                <p className="text-xs text-zinc-500 dark:text-zinc-400 mb-3">
                  Tell us what to adjust — e.g. &ldquo;make it more
                  concise&rdquo;, &ldquo;emphasize my experience with X&rdquo;,
                  or &ldquo;soften the tone&rdquo;. We&apos;ll regenerate using
                  your note, your base resume, and the full job posting.
                </p>
                <textarea
                  value={refinement}
                  onChange={(e) => setRefinement(e.target.value)}
                  rows={5}
                  placeholder="e.g. Make it more concise and professional; focus on my administrative experience."
                  className="w-full rounded-xl border border-zinc-300 dark:border-zinc-600 bg-white dark:bg-zinc-800 px-3 py-2 text-sm text-zinc-800 dark:text-zinc-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 resize-none"
                />
                <div className="flex items-center justify-end gap-2 mt-4">
                  <button
                    onClick={() => setFineTuneOpen(false)}
                    className="text-sm font-medium px-4 py-2 rounded-lg border border-zinc-300 dark:border-zinc-600 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleGenerateWithRefinement}
                    disabled={requesting}
                    className="text-sm font-semibold px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white transition-colors disabled:opacity-50"
                  >
                    {requesting ? "Regenerating…" : "Regenerate letter"}
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}

      {/* Unified preview overlay — top nav to switch between the resume and
          cover letter, plus version navigation. Conditionally mounted so it
          starts fresh each time it opens. */}
      {previewOpen && (
        <DocumentPreviewOverlay
          jobId={jobId}
          title={title}
          company={company}
          type="cover-letter"
          open={previewOpen}
          onClose={() => setPreviewOpen(false)}
        />
      )}
    </div>
  );
}
