"use client";

import {
  getJobDocumentStateAction,
  triggerCoverLetterAction,
} from "@/app/actions/documents";
import DocumentPreviewOverlay from "@/components/DocumentPreviewOverlay";
import DotLoader from "@/components/DotLoader";
import { useJobState } from "@/components/JobStateProvider";
import { useToast } from "@/components/Toast";
import { coverLetterStatusCopy } from "@/lib/funnel";
import { useEffect, useState } from "react";

const TONE_TEXT: Record<string, string> = {
  neutral: "text-zinc-500 dark:text-zinc-400",
  active: "text-violet-600 dark:text-violet-400",
  success: "text-emerald-600 dark:text-emerald-400",
  error: "text-rose-600 dark:text-rose-400",
};

/**
 * Cover letter for THIS job — generated by its OWN Azure Function + Service
 * Bus queue (`coverLetterWorker`), independent of the resume and evaluation.
 * For fit jobs it auto-generates when the evaluation scores the job; the
 * "Generate" button is the fallback/retry path.
 *
 * - `building` → shows "Writing your cover letter…" and listens live.
 * - `completed` → View (unified overlay) / Fine-tune.
 * - `none` → a Generate button.
 * - `failed` → error + Retry.
 *
 * A page refresh mid-generation re-hydrates `building`, so generation is
 * never cut off.
 */
export default function CoverLetterGenerationCard({
  jobId,
  title,
  company,
}: {
  jobId: string;
  title: string;
  company: string;
}) {
  // Shared live state (single socket + Realtime channel via JobStateProvider).
  const { coverLetterStatus, error: realtimeError } = useJobState();
  const toast = useToast();
  const [requesting, setRequesting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  // Optimistic local override: show "Writing…" immediately after triggering
  // instead of waiting for the Realtime/socket round-trip.
  const [optimisticBuilding, setOptimisticBuilding] = useState(false);
  // Unified preview overlay (Resume | Cover Letter tabs + version nav +
  // per-version fine-tune panel).
  const [previewOpen, setPreviewOpen] = useState(false);

  const status =
    coverLetterStatus === "completed" || coverLetterStatus === "failed"
      ? coverLetterStatus
      : optimisticBuilding || coverLetterStatus === "building"
        ? "building"
        : (coverLetterStatus ?? "none");
  const copy = coverLetterStatusCopy(status);
  const isBuilding = status === "building" || requesting;
  const isDone = status === "completed";
  const error = actionError ?? realtimeError;

  async function handleGenerate() {
    setActionError(null);
    setRequesting(true);
    const res = await triggerCoverLetterAction(jobId);
    setRequesting(false);
    if (!res.ok) {
      let msg: string;
      if (res.error.startsWith("LIMIT_REACHED:")) {
        msg = `${res.error.replace(/^LIMIT_REACHED:\s*/, "")} Upgrade on your Profile page for more.`;
      } else {
        msg = /resume/i.test(res.error)
          ? "Upload a resume first, then try again."
          : "Couldn't start your cover letter. Please try again in a moment.";
      }
      setActionError(msg);
      toast.error("Couldn't start", msg);
      return;
    }
    // Success → optimistically show "Writing your cover letter…" now.
    setOptimisticBuilding(true);
    toast.info(
      "Writing your cover letter",
      "Usually takes under a minute. You can leave this page.",
    );
  }

  // Guaranteed fallback while a cover letter is building: poll the document
  // state so the "Writing…" state ALWAYS clears to the real terminal state,
  // even if the socket/Realtime event is missed.
  useEffect(() => {
    if (coverLetterStatus !== "building" && !optimisticBuilding) return;
    let alive = true;
    async function check() {
      if (!alive) return;
      const res = await getJobDocumentStateAction(jobId);
      if (!alive || !res.ok) return;
      if (res.state.cover_letter_status === "completed") {
        setOptimisticBuilding(false);
      } else if (res.state.cover_letter_status === "failed") {
        setOptimisticBuilding(false);
        setActionError("The generation didn't finish. You can try again.");
      }
    }
    void check();
    const interval = setInterval(check, 3000);
    return () => {
      alive = false;
      clearInterval(interval);
    };
  }, [coverLetterStatus, optimisticBuilding, jobId]);

  return (
    <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5">
      <div className="flex items-center justify-between gap-3 mb-3">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-zinc-400 dark:text-zinc-500">
          Cover Letter
        </h2>
        <span className={`text-xs font-medium ${TONE_TEXT[copy.tone]}`}>
          {copy.label}
        </span>
      </div>

      {isBuilding ? (
        <div className="flex items-center gap-3">
          <DotLoader dotClassName="bg-violet-500" />
          <div>
            <p className="text-sm font-medium text-violet-700 dark:text-violet-300">
              Writing your cover letter for {company}
            </p>
            <p className="text-xs text-violet-500 dark:text-violet-400">
              Usually takes under a minute. You can leave this page.
            </p>
          </div>
        </div>
      ) : isDone ? (
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => setPreviewOpen(true)}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-xl bg-violet-600 hover:bg-violet-700 text-white shadow-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 focus-visible:ring-offset-1"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
              />
            </svg>
            View cover letter
          </button>
          <button
            type="button"
            onClick={() => setPreviewOpen(true)}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg border border-zinc-300 dark:border-zinc-600 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
              />
            </svg>
            Fine-tune
          </button>
        </div>
      ) : (
        <>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-4">
            Generate a cover letter for {title} at {company} — addressed to the
            role and grounded in your resume.
          </p>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={requesting}
            className="inline-flex items-center gap-2 text-sm font-medium px-4 py-2 rounded-xl border border-violet-200 dark:border-violet-800 text-violet-700 dark:text-violet-300 hover:bg-violet-50 dark:hover:bg-violet-950/60 transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-violet-500 focus-visible:ring-offset-1 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 4v16m8-8H4"
              />
            </svg>
            {requesting ? "Starting…" : "Generate cover letter"}
          </button>
        </>
      )}

      {error && (
        <p className="mt-3 text-xs text-red-600 dark:text-red-400">{error}</p>
      )}

      {/* Unified preview overlay — top nav to switch between the resume and
          cover letter, version tabs with live status, and the in-overlay
          fine-tune panel. Conditionally mounted so it starts fresh each time
          it opens. */}
      {previewOpen && (
        <DocumentPreviewOverlay
          jobId={jobId}
          title={title}
          company={company}
          type="cover-letter"
          open={previewOpen}
          onClose={() => setPreviewOpen(false)}
        />
      )}
    </div>
  );
}
