"use client";

import { triggerCoverLetterAction } from "@/app/actions/documents";
import DotLoader from "@/components/DotLoader";
import { useJobState } from "@/components/JobStateProvider";
import { coverLetterStatusCopy } from "@/lib/funnel";
import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import { useState } from "react";

const TONE_TEXT: Record<string, string> = {
  neutral: "text-zinc-500 dark:text-zinc-400",
  active: "text-indigo-600 dark:text-indigo-400",
  success: "text-emerald-600 dark:text-emerald-400",
  error: "text-rose-600 dark:text-rose-400",
};

/**
 * Strip LLM/editor placeholder junk from a cover letter so it never leaks to
 * the user. Handles things like "#attachment:Pasted text #1", markdown image
 * embeds, code fences, and stray "[attachment ...]" tokens that some legacy
 * generations contained.
 */
function sanitizeLetter(raw: string): string {
  let s = raw;
  // "#attachment:Pasted text #1" / "#attachment: ..." placeholders
  s = s.replace(/#attachment:\s*[^\n]*/gi, "");
  // Markdown image embeds: ![alt](url)
  s = s.replace(/!\[[^\]]*\]\([^)]*\)/g, "");
  // "[attachment ...]" / "[image ...]" tokens
  s = s.replace(/\[(?:attachment|image|paste)[^\]]*\]/gi, "");
  // Fenced code blocks
  s = s.replace(/```[\s\S]*?```/g, "");
  // Collapse 3+ blank lines
  s = s.replace(/\n{3,}/g, "\n\n");
  return s.trim();
}

async function buildDocx(
  letter: string,
  title: string,
  company: string,
): Promise<Blob> {
  const lines = letter.split("\n");
  const paragraphs: Paragraph[] = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed === "") {
      paragraphs.push(new Paragraph({ text: "" }));
    } else {
      paragraphs.push(
        new Paragraph({
          children: [new TextRun({ text: trimmed, size: 24, font: "Calibri" })],
          spacing: { after: 120 },
          alignment: AlignmentType.LEFT,
        }),
      );
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: `Cover Letter — ${title}`,
                bold: true,
                size: 32,
                font: "Calibri",
                color: "1D4ED8",
              }),
            ],
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 80 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: company,
                size: 24,
                font: "Calibri",
                color: "6B7280",
              }),
            ],
            spacing: { after: 400 },
          }),
          new Paragraph({
            border: {
              bottom: { color: "DBEAFE", style: BorderStyle.SINGLE, size: 8 },
            },
            spacing: { after: 400 },
            text: "",
          }),
          ...paragraphs,
        ],
      },
    ],
  });

  return Packer.toBlob(doc);
}

/**
 * Cover letter for THIS job — generated by its OWN Azure Function + Service
 * Bus queue (`coverLetterWorker`), independent of the resume and evaluation.
 * For fit jobs it auto-generates when the evaluation scores the job; the
 * "Generate" button is the fallback/retry path.
 *
 * - `building` → shows "Writing your cover letter…" and listens live.
 * - `completed` → View (modal) / Copy / Download DOCX.
 * - `none` → a Generate button.
 * - `failed` → error + Retry.
 *
 * A page refresh mid-generation re-hydrates `building`, so generation is
 * never cut off.
 */
export default function CoverLetterGenerationCard({
  jobId,
  title,
  company,
}: {
  jobId: string;
  title: string;
  company: string;
}) {
  // Shared live state (single socket + Realtime channel via JobStateProvider).
  const {
    coverLetterStatus,
    coverLetter,
    error: realtimeError,
  } = useJobState();
  const [requesting, setRequesting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);
  // Optimistic local override: show "Writing…" immediately after triggering
  // instead of waiting for the Realtime/socket round-trip.
  const [optimisticBuilding, setOptimisticBuilding] = useState(false);

  const status =
    coverLetterStatus === "completed" || coverLetterStatus === "failed"
      ? coverLetterStatus
      : optimisticBuilding || coverLetterStatus === "building"
        ? "building"
        : (coverLetterStatus ?? "none");
  const copy = coverLetterStatusCopy(status);
  const isBuilding = status === "building" || requesting;
  const isDone = status === "completed" && !!coverLetter;
  const error = actionError ?? realtimeError;

  async function handleGenerate() {
    setActionError(null);
    setRequesting(true);
    const res = await triggerCoverLetterAction(jobId);
    setRequesting(false);
    if (!res.ok) {
      setActionError(
        /resume/i.test(res.error)
          ? "Upload a resume first, then try again."
          : "Couldn't start your cover letter. Please try again in a moment.",
      );
      return;
    }
    // Success → optimistically show "Writing your cover letter…" now.
    setOptimisticBuilding(true);
  }

  async function handleCopy() {
    if (!coverLetter) return;
    await navigator.clipboard.writeText(sanitizeLetter(coverLetter));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  async function handleDownload() {
    if (!coverLetter) return;
    setDownloading(true);
    try {
      const blob = await buildDocx(sanitizeLetter(coverLetter), title, company);
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `cover-letter-${company
        .replace(/\s+/g, "-")
        .toLowerCase()}.docx`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setDownloading(false);
    }
  }

  return (
    <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5">
      <div className="flex items-center justify-between gap-3 mb-3">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-zinc-400 dark:text-zinc-500">
          Cover Letter
        </h2>
        <span className={`text-xs font-medium ${TONE_TEXT[copy.tone]}`}>
          {copy.label}
        </span>
      </div>

      {isBuilding ? (
        <div className="flex items-center gap-3">
          <DotLoader dotClassName="bg-indigo-500" />
          <div>
            <p className="text-sm font-medium text-indigo-700 dark:text-indigo-300">
              Writing your cover letter for {company}
            </p>
            <p className="text-xs text-indigo-500 dark:text-indigo-400">
              Usually takes under a minute. You can leave this page.
            </p>
          </div>
        </div>
      ) : isDone ? (
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => setModalOpen(true)}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
              />
            </svg>
            View cover letter
          </button>
          <button
            type="button"
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg border border-zinc-300 dark:border-zinc-600 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors"
          >
            {copied ? (
              <>
                <svg
                  className="w-4 h-4 text-emerald-500"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M5 13l4 4L19 7"
                  />
                </svg>
                Copied!
              </>
            ) : (
              <>
                <svg
                  className="w-4 h-4"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
                Copy
              </>
            )}
          </button>
          <button
            type="button"
            onClick={handleDownload}
            disabled={downloading}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg border border-blue-300 dark:border-blue-700 text-blue-700 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/40 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {downloading ? "Exporting…" : "Download Word"}
          </button>
        </div>
      ) : (
        <>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-4">
            Generate a cover letter for {title} at {company} — addressed to the
            role and grounded in your resume.
          </p>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={requesting}
            className="inline-flex items-center gap-2 text-sm font-medium px-4 py-2 rounded-xl border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 hover:bg-indigo-50 dark:hover:bg-indigo-950/60 transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 4v16m8-8H4"
              />
            </svg>
            {requesting ? "Starting…" : "Generate cover letter"}
          </button>
        </>
      )}

      {error && (
        <p className="mt-3 text-xs text-red-600 dark:text-red-400">{error}</p>
      )}

      {/* Cover letter modal */}
      {modalOpen && coverLetter && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
          onClick={() => setModalOpen(false)}
        >
          <div
            className="relative w-full max-w-2xl max-h-[85vh] flex flex-col rounded-2xl bg-white dark:bg-zinc-900 shadow-2xl border border-zinc-200 dark:border-zinc-700"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between px-6 py-4 border-b border-zinc-200 dark:border-zinc-700 shrink-0">
              <span className="text-sm font-semibold text-blue-700 dark:text-blue-400">
                Cover Letter
              </span>
              <button
                onClick={() => setModalOpen(false)}
                className="flex items-center justify-center w-8 h-8 rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800 text-zinc-500 dark:text-zinc-400 transition-colors"
                aria-label="Close"
              >
                <svg
                  className="w-5 h-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </button>
            </div>
            <div className="overflow-y-auto p-6">
              <p className="text-sm leading-7 text-zinc-700 dark:text-zinc-300 whitespace-pre-wrap">
                {sanitizeLetter(coverLetter)}
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
