"use client";

import { triggerResumeAction } from "@/app/actions/documents";
import DotLoader from "@/components/DotLoader";
import { useJobState } from "@/components/JobStateProvider";
import ResumePreviewOverlay from "@/components/ResumePreviewOverlay";
import { resumeStatusCopy } from "@/lib/funnel";
import { useState } from "react";

const TONE_TEXT: Record<string, string> = {
  neutral: "text-zinc-500 dark:text-zinc-400",
  active: "text-indigo-600 dark:text-indigo-400",
  success: "text-emerald-600 dark:text-emerald-400",
  error: "text-rose-600 dark:text-rose-400",
};

/**
 * Tailored resume for THIS job — generated by its OWN Azure Function +
 * Service Bus queue (`resumeWorker`), fully decoupled from the evaluation.
 * For fit jobs it auto-generates when the evaluation scores the job; the
 * "Generate" button is the fallback/retry path.
 *
 * - `building` → shows "Generating…" and listens live via Realtime + socket.
 * - `completed` → View (overlay) / Download PDF buttons.
 * - `none` → a Generate button (the fit auto-build didn't start, or this is
 *   a not-fit job the user wants a resume for anyway).
 * - `failed` → a clear error + a Retry button.
 *
 * A page refresh mid-generation re-hydrates `building` from Supabase, so the
 * generation continues server-side and is never cut off.
 */
export default function ResumeGenerationCard({
  jobId,
  title,
  company,
}: {
  jobId: string;
  title: string;
  company: string;
}) {
  // Shared live state (single socket + Realtime channel via JobStateProvider).
  const { resumeStatus, resumeUrl, error: realtimeError } = useJobState();
  const [requesting, setRequesting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  // Optimistic local override: while the Azure function enqueues + the worker
  // builds, we show "Generating…" immediately instead of waiting for the
  // Realtime/socket event to round-trip (which can take 30-60s for a resume).
  const [optimisticBuilding, setOptimisticBuilding] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);
  // Fine-tune overlay: user enters a refinement note, we regenerate the resume
  // with that instruction appended to the prompt.
  const [fineTuneOpen, setFineTuneOpen] = useState(false);
  const [refinement, setRefinement] = useState("");

  async function handleGenerateWithRefinement() {
    const note = refinement.trim();
    if (!note) {
      setActionError("Tell us what to change before regenerating.");
      return;
    }
    setActionError(null);
    setFineTuneOpen(false);
    setRequesting(true);
    const res = await triggerResumeAction(jobId, note);
    setRequesting(false);
    if (!res.ok) {
      setActionError(
        /resume/i.test(res.error)
          ? "Upload a resume first, then try again."
          : "Couldn't regenerate your resume. Please try again in a moment.",
      );
      return;
    }
    setOptimisticBuilding(true);
    setRefinement("");
  }

  // A terminal server state (completed/failed) supersedes the optimistic flag;
  // otherwise a `building` state from Realtime also supersedes it.
  const status =
    resumeStatus === "completed" || resumeStatus === "failed"
      ? resumeStatus
      : optimisticBuilding || resumeStatus === "building"
        ? "building"
        : (resumeStatus ?? "none");
  const copy = resumeStatusCopy(status);
  const isBuilding = status === "building" || requesting;
  const isDone = status === "completed" && !!resumeUrl;
  const error = actionError ?? realtimeError;

  async function handleGenerate() {
    setActionError(null);
    setRequesting(true);
    const res = await triggerResumeAction(jobId);
    setRequesting(false);
    if (!res.ok) {
      setActionError(
        /resume/i.test(res.error)
          ? "Upload a resume first, then try again."
          : "Couldn't start your resume. Please try again in a moment.",
      );
      return;
    }
    // Success → optimistically show "Generating…" now. Realtime/socket will
    // confirm `building` → `completed` (or `failed`) and clear this flag.
    setOptimisticBuilding(true);
  }

  return (
    <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5">
      <div className="flex items-center justify-between gap-3 mb-3">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-zinc-400 dark:text-zinc-500">
          Tailored Resume
        </h2>
        <span className={`text-xs font-medium ${TONE_TEXT[copy.tone]}`}>
          {copy.label}
        </span>
      </div>

      {isBuilding ? (
        <div className="flex items-center gap-3">
          <DotLoader dotClassName="bg-indigo-500" />
          <div>
            <p className="text-sm font-medium text-indigo-700 dark:text-indigo-300">
              Tailoring your resume for {company}
            </p>
            <p className="text-xs text-indigo-500 dark:text-indigo-400">
              This usually takes a minute. You can leave this page — we&apos;ll
              update you here.
            </p>
          </div>
        </div>
      ) : isDone ? (
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => setPreviewOpen(true)}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
              />
            </svg>
            View resume
          </button>
          <button
            type="button"
            onClick={() => setFineTuneOpen(true)}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg border border-zinc-300 dark:border-zinc-600 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
              />
            </svg>
            Fine-tune
          </button>
        </div>
      ) : (
        <>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-4">
            Generate a resume tailored to {title} at {company} — grounded in
            your uploaded resume.
          </p>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={requesting}
            className="inline-flex items-center gap-2 text-sm font-medium px-4 py-2 rounded-xl border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 hover:bg-indigo-50 dark:hover:bg-indigo-950/60 transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 4v16m8-8H4"
              />
            </svg>
            {requesting ? "Starting…" : "Generate tailored resume"}
          </button>
        </>
      )}

      {error && (
        <p className="mt-3 text-xs text-red-600 dark:text-red-400">{error}</p>
      )}

      {/* Fine-tune overlay — user tells us what to change, we regenerate the
          resume with that note (plus the base resume + full job content). */}
      {fineTuneOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
          onClick={() => setFineTuneOpen(false)}
        >
          <div
            className="relative w-full max-w-lg rounded-2xl bg-white dark:bg-zinc-900 shadow-2xl border border-zinc-200 dark:border-zinc-700 p-6"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-zinc-900 dark:text-zinc-50">
                Fine-tune your resume
              </h3>
              <button
                onClick={() => setFineTuneOpen(false)}
                className="flex items-center justify-center w-8 h-8 rounded-lg hover:bg-zinc-100 dark:hover:bg-zinc-800 text-zinc-500 dark:text-zinc-400 transition-colors"
                aria-label="Close"
              >
                <svg
                  className="w-5 h-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={2}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M6 18L18 6M6 6l12 12"
                  />
                </svg>
              </button>
            </div>
            <p className="text-xs text-zinc-500 dark:text-zinc-400 mb-3">
              Tell us what to adjust — e.g. &ldquo;make it more concise&rdquo;,
              &ldquo;emphasize my data-entry experience&rdquo;, or &ldquo;fix
              the wording of the summary&rdquo;. We&apos;ll regenerate using
              your note, your base resume, and the full job posting.
            </p>
            <textarea
              value={refinement}
              onChange={(e) => setRefinement(e.target.value)}
              rows={5}
              placeholder="e.g. Emphasize my document processing and Excel skills; keep it to one page."
              className="w-full rounded-xl border border-zinc-300 dark:border-zinc-600 bg-white dark:bg-zinc-800 px-3 py-2 text-sm text-zinc-800 dark:text-zinc-100 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 resize-none"
            />
            <div className="flex items-center justify-end gap-2 mt-4">
              <button
                onClick={() => setFineTuneOpen(false)}
                className="text-sm font-medium px-4 py-2 rounded-lg border border-zinc-300 dark:border-zinc-600 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleGenerateWithRefinement}
                disabled={requesting}
                className="text-sm font-semibold px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-700 text-white transition-colors disabled:opacity-50"
              >
                {requesting ? "Regenerating…" : "Regenerate resume"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Resume preview overlay (not a new browser tab). Conditionally
          mounted so it starts fresh (no stale HTML) each time it opens. */}
      {previewOpen && (
        <ResumePreviewOverlay
          jobId={jobId}
          open={previewOpen}
          onClose={() => setPreviewOpen(false)}
        />
      )}
    </div>
  );
}
