"use client";

import { triggerResumeAction } from "@/app/actions/documents";
import DotLoader from "@/components/DotLoader";
import { useJobState } from "@/components/JobStateProvider";
import ResumePreviewOverlay from "@/components/ResumePreviewOverlay";
import { resumeStatusCopy } from "@/lib/funnel";
import { useState } from "react";

const TONE_TEXT: Record<string, string> = {
  neutral: "text-zinc-500 dark:text-zinc-400",
  active: "text-indigo-600 dark:text-indigo-400",
  success: "text-emerald-600 dark:text-emerald-400",
  error: "text-rose-600 dark:text-rose-400",
};

/**
 * Tailored resume for THIS job — generated by its OWN Azure Function +
 * Service Bus queue (`resumeWorker`), fully decoupled from the evaluation.
 * For fit jobs it auto-generates when the evaluation scores the job; the
 * "Generate" button is the fallback/retry path.
 *
 * - `building` → shows "Generating…" and listens live via Realtime + socket.
 * - `completed` → View (overlay) / Download PDF buttons.
 * - `none` → a Generate button (the fit auto-build didn't start, or this is
 *   a not-fit job the user wants a resume for anyway).
 * - `failed` → a clear error + a Retry button.
 *
 * A page refresh mid-generation re-hydrates `building` from Supabase, so the
 * generation continues server-side and is never cut off.
 */
export default function ResumeGenerationCard({
  jobId,
  title,
  company,
}: {
  jobId: string;
  title: string;
  company: string;
}) {
  // Shared live state (single socket + Realtime channel via JobStateProvider).
  const { resumeStatus, resumeUrl, error: realtimeError } = useJobState();
  const [requesting, setRequesting] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  // Optimistic local override: while the Azure function enqueues + the worker
  // builds, we show "Generating…" immediately instead of waiting for the
  // Realtime/socket event to round-trip (which can take 30-60s for a resume).
  const [optimisticBuilding, setOptimisticBuilding] = useState(false);
  const [previewOpen, setPreviewOpen] = useState(false);

  // A terminal server state (completed/failed) supersedes the optimistic flag;
  // otherwise a `building` state from Realtime also supersedes it.
  const status =
    resumeStatus === "completed" || resumeStatus === "failed"
      ? resumeStatus
      : optimisticBuilding || resumeStatus === "building"
        ? "building"
        : (resumeStatus ?? "none");
  const copy = resumeStatusCopy(status);
  const isBuilding = status === "building" || requesting;
  const isDone = status === "completed" && !!resumeUrl;
  const error = actionError ?? realtimeError;

  async function handleGenerate() {
    setActionError(null);
    setRequesting(true);
    const res = await triggerResumeAction(jobId);
    setRequesting(false);
    if (!res.ok) {
      setActionError(
        /resume/i.test(res.error)
          ? "Upload a resume first, then try again."
          : "Couldn't start your resume. Please try again in a moment.",
      );
      return;
    }
    // Success → optimistically show "Generating…" now. Realtime/socket will
    // confirm `building` → `completed` (or `failed`) and clear this flag.
    setOptimisticBuilding(true);
  }

  async function downloadPdf() {
    const html = await fetchResumeHtml();
    if (!html) {
      setActionError("Couldn't prepare the PDF. Please try again in a moment.");
      return;
    }
    const iframe = document.createElement("iframe");
    iframe.style.position = "fixed";
    iframe.style.right = "0";
    iframe.style.bottom = "0";
    iframe.style.width = "0";
    iframe.style.height = "0";
    iframe.style.border = "0";
    document.body.appendChild(iframe);
    const doc = iframe.contentDocument;
    if (!doc) {
      iframe.remove();
      return;
    }
    doc.open();
    doc.write(html);
    doc.close();
    const finish = () => {
      try {
        iframe.contentWindow?.focus();
        iframe.contentWindow?.print();
      } finally {
        setTimeout(() => iframe.remove(), 1000);
      }
    };
    if (doc.readyState === "complete") finish();
    else
      doc.addEventListener("readystatechange", () => {
        if (doc.readyState === "complete") finish();
      });
  }

  /**
   * Fetch the resume HTML — preferring the auth-scoped API route, falling
   * back to the direct storage URL (e.g. when the route 404s for a legacy
   * row). Never downloads a broken/empty/garbage file.
   */
  async function fetchResumeHtml(): Promise<string | null> {
    const candidates = [`/api/resume/${jobId}`, resumeUrl].filter(
      (u): u is string => !!u,
    );
    for (const url of candidates) {
      try {
        const res = await fetch(url, { cache: "no-store" });
        if (!res.ok) continue;
        const text = await res.text();
        // Guard: reject JSON error bodies or placeholder-only content.
        if (
          text.trim().startsWith("{") ||
          !text.trim() ||
          /#attachment|Pasted text/i.test(text)
        ) {
          continue;
        }
        return text;
      } catch {
        continue;
      }
    }
    return null;
  }

  return (
    <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5">
      <div className="flex items-center justify-between gap-3 mb-3">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-zinc-400 dark:text-zinc-500">
          Tailored Resume
        </h2>
        <span className={`text-xs font-medium ${TONE_TEXT[copy.tone]}`}>
          {copy.label}
        </span>
      </div>

      {isBuilding ? (
        <div className="flex items-center gap-3">
          <DotLoader dotClassName="bg-indigo-500" />
          <div>
            <p className="text-sm font-medium text-indigo-700 dark:text-indigo-300">
              Tailoring your resume for {company}
            </p>
            <p className="text-xs text-indigo-500 dark:text-indigo-400">
              This usually takes a minute. You can leave this page — we&apos;ll
              update you here.
            </p>
          </div>
        </div>
      ) : isDone ? (
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => setPreviewOpen(true)}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white shadow-sm transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
              />
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
              />
            </svg>
            View resume
          </button>
          <button
            type="button"
            onClick={downloadPdf}
            className="inline-flex items-center gap-1.5 text-sm font-medium px-4 py-2 rounded-lg border border-emerald-300 dark:border-emerald-700 text-emerald-700 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-900/40 transition-colors"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
              />
            </svg>
            Download PDF
          </button>
        </div>
      ) : (
        <>
          <p className="text-sm text-zinc-500 dark:text-zinc-400 mb-4">
            Generate a resume tailored to {title} at {company} — grounded in
            your uploaded resume.
          </p>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={requesting}
            className="inline-flex items-center gap-2 text-sm font-medium px-4 py-2 rounded-xl border border-indigo-200 dark:border-indigo-800 text-indigo-700 dark:text-indigo-300 hover:bg-indigo-50 dark:hover:bg-indigo-950/60 transition-all focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-1 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <svg
              className="w-4 h-4"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 4v16m8-8H4"
              />
            </svg>
            {requesting ? "Starting…" : "Generate tailored resume"}
          </button>
        </>
      )}

      {error && (
        <p className="mt-3 text-xs text-red-600 dark:text-red-400">{error}</p>
      )}

      {/* Resume preview overlay (not a new browser tab). Conditionally
          mounted so it starts fresh (no stale HTML) each time it opens. */}
      {previewOpen && (
        <ResumePreviewOverlay
          jobId={jobId}
          open={previewOpen}
          onClose={() => setPreviewOpen(false)}
        />
      )}
    </div>
  );
}
